### ISSUE TITLE
Link5 Inertia Mismatch

### ISSUE THREAD

**Issue by kevinzakka** [JeanElsner/panda_mujoco#6]
Hi Jean,

Looks like [your](https://github.com/JeanElsner/panda_mujoco/blob/master/panda.xml#L51) inertial position for link5 doesn't match the franka_ros one, see [here](https://github.com/frankaemika/franka_ros/blob/develop/franka_description/robots/inertial.yaml#L75).

**Comment by JeanElsner** [comment]
Hi Kevin,

sorry for the late reply. They seem to have fixed that by [now](https://github.com/frankaemika/franka_ros/blob/develop/franka_description/robots/common/inertial.yaml).
By the way I took the parameters directly from [here](https://raw.githubusercontent.com/marcocognetti/FrankaEmikaPandaDynModel/master/pdf/RA-L_2019_PandaDynIdent_SUPPLEMENTARY_MATERIAL.pdf).

Edit: My mistake, you're right there is a sign missing in my position, thanks!
